### ISSUE TITLE
User story 1: 

### ISSUE THREAD

**Issue by Quetzaly88** [Quetzaly88/surf_spots#1]
### User Story:
As a **user** I want to **create and account and log in** so that **I can post and comment about surf spots**

### Acceptance Criteria
- [ ] Criterion 1: The user will be able to create an account with an email, username and password. 
- [ ] Criterion 2: The user can log in with its credentials. 
- [ ] Criterion 3: When invalif information is inserted, an error message will appear. 
- [ ] Criterion 4: The user can log out from its account. 

### Tasks
- [ ] Task 1: Create the user model and a database schema. 
- [ ] Task 2: Develop registration form and validation. 
- [ ] Task 3: Create a log in with backend functionality.
- [ ] Task 4: Add error messages for invalid inputs. 
- [ ] Task 5: Write Python tests for registration and functionality. 
- [ ] Task 6: Use Javascript for form validation.
