### ISSUE TITLE
User story 3:

### ISSUE THREAD

**Issue by Quetzaly88** [Quetzaly88/surf_spots#3]
### User Story 3:
As a **user** I can **comment on posts from other users ** so that **we can discuss obout it.**

### Acceptance Criteria
- [ ] Criterion 1: A user can add comments to a post.
- [ ] Criterion 2: Comments are displayed below the post with time and date. 
- [ ] Criterion 3: Just the users that are loged in can comment others posts. 

### Tasks
- [ ] Task 1: Create the "Comment model" with fields for the text, associated post, user, and timestamp. 
- [ ] Task 2: Develop the comment form on the post detail page. 
- [ ] Task 3: Implement validation for comments submission as no empty text and not longer than 1000 characters. 
- [ ] Task 4: Display the list of comments under each post. 
- [ ] Task 5: Write Python tests for the "Comment model" and comment creation. 
- [ ] Task 5: Write Javascript for form interactions.
