### ISSUE TITLE
User story:

### ISSUE THREAD

**Issue by Quetzaly88** [Quetzaly88/surf_spots#4]
### User Story 4:
As a **user** I want to  **filter surf spots by categories** so that **I can find surf spots suited to my skills**

### Acceptance Criteria
- [ ] Criterion 1: The surf spots should be categorized on beginner, advanced and for everyone. 
- [ ] Criterion 2: A dropdown menu or sidebar allows user to filter those posts by category. 

### Tasks
- [ ] Task 1: Update the "SurfSpot" model to include a "category" field. 
- [ ] Task 2: Create a dropdown menu for the different options.
- [ ] Task 3: Update the homepage to display filtered results. 
- [ ] Task 4: Add backend functionality to query posts by category. 
- [ ] Task 5: Write Python tests for category filtering functionality.
