### ISSUE TITLE
User story 6: Responsive design

### ISSUE THREAD

**Issue by Quetzaly88** [Quetzaly88/surf_spots#6]
### User Story 6: 
As a **user**,  I want, **that the website works on my mobile** so that **I can browse surfs pots on the go**

### Acceptance Criteria
- [ ] Criterion 1: Full responsive website.
- [ ] Criterion 2: Pages doesn't loose functionality in different devices. 
- [ ] Criterion 3: Buttons, forms and texts are accessible and usable on mobile. 

### Tasks
- [ ] Task 1: Use bootstrap for a responsive layout. 
- [ ] Task 2: Test all pages on multiple screen sizes. 
- [ ] Task 3: Test responsiveness.
