### ISSUE TITLE
User story 7: Deployment

### ISSUE THREAD

**Issue by Quetzaly88** [Quetzaly88/surf_spots#7]
### User Story 7: 
As a **developer** I want **to deploy the application to Heroku** so that **it is accessible online**

### Acceptance Criteria
- [ ] Criterion 1: The application is deployed on Heroku. 
- [ ] Criterion 2: All environment variables are securely stored. 
- [ ] Criterion 3: Debug mode is off in production. 

### Tasks
- [ ] Task 1: Create new application on Heroku. 
- [ ] Task 2: Install and configure "gunicorn" and "whitenoise" for deployment. 
- [ ] Task 3: Configure environment variables for Heroku. 
- [ ] Task 4: Document the deployment steps in the README. 
- [ ] Task 5: Test deployed application for functionality and responsiveness.
